services:
  virtual-can-bus:
    image: gianlucabresolin/virtual-can-bus:latest
    platform: linux/arm64
    container_name: virtual-can-bus
    profiles: ["default", "debug-state"]
    networks:
      - can-net

  virtual-can-bus-debug:
    image: gianlucabresolin/virtual-can-bus-debug:latest
    platform: linux/arm64
    container_name: virtual-can-bus
    profiles: ["debug-verbose"]
    networks:
      - can-net

  victim-device:
    image: gianlucabresolin/can-device:victim
    platform: linux/arm64
    container_name: victim-device
    profiles: ["default"]
    depends_on:
      - virtual-can-bus
    networks:
      - can-net

  victim-device-debug-state:
    image: gianlucabresolin/can-device-debug-state:victim
    platform: linux/arm64
    container_name: victim-device
    profiles: ["debug-state"]
    depends_on:
      - virtual-can-bus
    networks:
      - can-net

  victim-device-debug-verbose:
    image: gianlucabresolin/can-device-debug-verbose:victim
    platform: linux/arm64
    container_name: victim-device
    profiles: ["debug-verbose"]
    depends_on:
      - virtual-can-bus-debug
    networks:
      - can-net

  attacker-device:
    image: gianlucabresolin/can-device:attacker
    platform: linux/arm64
    container_name: attacker-device
    profiles: ["default"]
    depends_on:
      - virtual-can-bus
    networks:
      - can-net

  attacker-device-debug-state:
    image: gianlucabresolin/can-device-debug-state:attacker
    platform: linux/arm64
    container_name: attacker-device
    profiles: ["debug-state"]
    depends_on:
      - virtual-can-bus
    networks:
      - can-net

  attacker-device-debug-verbose:
    image: gianlucabresolin/can-device-debug-verbose:attacker
    platform: linux/arm64
    container_name: attacker-device
    profiles: ["debug-verbose"]
    depends_on:
      - virtual-can-bus-debug
    networks:
      - can-net

  led-device:
    image: gianlucabresolin/can-device:led
    platform: linux/arm64
    container_name: led-device
    profiles: ["default"]
    depends_on:
      - virtual-can-bus
    networks:
      - can-net

  led-device-debug-state:
    image: gianlucabresolin/can-device-debug-state:led
    platform: linux/arm64
    container_name: led-device
    profiles: ["debug-state"]
    depends_on:
      - virtual-can-bus
    networks:
      - can-net

  led-device-debug-verbose:
    image: gianlucabresolin/can-device-debug-verbose:led
    platform: linux/arm64
    container_name: led-device
    profiles: ["debug-verbose"]
    depends_on:
      - virtual-can-bus-debug
    networks:
      - can-net

networks:
  can-net:
    driver: bridge