version: "3.8"

services:
  virtual-can-bus:
    image: virtual-can-bus:latest
    container_name: virtual-can-bus
    command: >
      - "cargo run --release --bin virtual-can-bus"

  victim-device:
    image: device:latest
    environment:
      - MY_IDS=0x100
      - INTERESTED_IDS = ""
    container_name: victim-device

  attacker-device:
    image: device:latest
    environment:
      - MY_IDS=0x100
      - INTERESTED_IDS = ""
    container_name: attacker-device

  other-device:
    image: device:latest
    environment:
      - MY_IDS=0x200
      - INTERESTED_IDS=0x100
    container_name: other-device