[build]
target = "thumbv7m-none-eabi"

[target.thumbv7m-none-eabi]
runner = """
    ./qemu-custom/build/qemu-system-arm-unsigned \
    -machine lm3s6965evb \
    -cpu cortex-m3 \
    -nographic \
    -semihosting \
    -kernel  
    """
rustflags = [
    "-C", "link-arg=-Tlink.x"       
]